POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Pena",
  "username": "pena100",
  "password": "password",
  "email": "p.ena@mail.com",
  "role": "admin"
}

### Post login
POST http://localhost:3000/api/v1/auth/login
content-type: application/json

{
  "username": "pena100",
  "password": "password"
}

### Get my user info
GET http://localhost:3000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozOCwibmFtZSI6IlBlbmEiLCJ1c2VybmFtZSI6InBlbmExMDAiLCJlbWFpbCI6InAuZW5hQG1haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzEyOTE3MTg5LCJleHAiOjE3MTMwMDM1ODl9.Z9vujt9nNIH1HXJQoXOXMha3EdVNqV0SYClJZYzWy3o
